import esbuild from "esbuild";
import { builtinModules } from "node:module";
import process from "node:process";
import { readFileSync } from "node:fs";

const builtins = [...builtinModules, ...builtinModules.map(m => `node:${m}`)];

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const pkg = JSON.parse(readFileSync("./package.json", "utf8"));
const version = pkg.version;

const bridgeParams = {
    banner: {
        js: "#!/usr/bin/env node\n" + banner,
    },
    entryPoints: ["src/mcp-bridge.ts"],
    bundle: true,
    platform: "node",
    external: [...builtins],
    format: "cjs",
    logLevel: "info",
    target: "node18",
    treeShaking: true,
    sourcemap: prod ? false : "inline",
    minify: prod,
    outfile: "mcp-bridge.js",
    define: {
        "__VERSION__": JSON.stringify(version),
    },
};

await esbuild.build(bridgeParams).catch((x) => {
    if (x.errors) {
        console.error(x.errors);
    } else {
        console.error(x);
    }
    process.exit(1);
});
